apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: stress
          image: wdhif/stress-ng
          args:
            ["--aggressive", "--cpu", "4", "--vm", "4", "--vm-bytes", "450M"]
          resources:
            requests:
              memory: "2000Mi"
              cpu: "4"
            limits:
              memory: "2000Mi"
              cpu: "4"
