apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: inflate
          image: mcr.microsoft.com/oss/kubernetes/pause:3.6
          resources:
            requests:
              memory: "200Mi"
              cpu: "0.5"
            limits:
              memory: "200Mi"
              cpu: "0.5"
