apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 50
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: stress
          image: wdhif/stress-ng
          args:
            ["--aggressive", "--cpu", "1", "--vm", "1", "--vm-bytes", "200M"]
          resources:
            requests:
              memory: "200Mi"
              cpu: "0.5"
            limits:
              memory: "200Mi"
              cpu: "0.5"
