apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleTier
spec:
  replicas: 20
  selector:
    matchLabels:
      app: middleTier
  template:
    metadata:
      labels:
        app: middleTier
    spec:
      containers:
        - name: stress
          image: progrium/stress
          args: ["--cpu", "2", "--vm-bytes", "800M"]

          resources:
            requests:
              memory: "800Mi"
              cpu: "2"
            limits:
              memory: "800Mi"
              cpu: "2"
