apiVersion: apps/v1
kind: Deployment
metadata:
  name: middletier
spec:
  replicas: 20
  selector:
    matchLabels:
      app: middleTier
  template:
    metadata:
      labels:
        app: middleTier
    spec:
      containers:
        - name: stress
          image: wdhif/stress-ng
          args:
            ["--aggressive", "--cpu", "2", "--vm", "4", "--vm-bytes", "200M"]

          resources:
            requests:
              memory: "1000Mi"
              cpu: "2"
            limits:
              memory: "1000Mi"
              cpu: "2"
